output   = "src/backend/dbmodels"
pkgname  = "dbmodels"

[psql]
  dbname = "gosvelte"
  host   = "localhost"
  port   = 5450
  user   = "root"
  pass   = "secret"
  sslmode = "disable"
  schema = "public"
  blacklist = [
      "django_migrations",
  ]
